#pragma once

#define UseAllDisplaysKey "General_UseAllDisplays"
#define WinScoreKey "General_WinScore"
#define Paddle1RKey "Color_Paddle1_R"
#define Paddle1GKey "Color_Paddle1_G"
#define Paddle1BKey "Color_Paddle1_B"
#define Paddle2RKey "Color_Paddle2_R"
#define Paddle2GKey "Color_Paddle2_G"
#define Paddle2BKey "Color_Paddle2_B"
#define BallRKey "Color_Ball_R"
#define BallGKey "Color_Ball_G"
#define BallBKey "Color_Ball_B"
#define Paddle1UpKey "Keyboard_Paddle1_UpKey"
#define Paddle1DownKey "Keyboard_Paddle1_DownKey"
#define Paddle2UpKey "Keyboard_Paddle2_UpKey"
#define Paddle2DownKey "Keyboard_Paddle2_DownKey"
#define QuitKey "Keyboard_Quit"